### ISSUE TITLE
Integrate pokémon/move/ability/etc. data scraped from PokéDex with MongoDB.

### ISSUE THREAD

**Issue by skylar32** [nbely/turq-bot#2]
We need to scrape as much information as possible from the [Phoenixdex website](https://phoenixdex.alteredorigin.net) and turn it into usable data that can be stored in our MongoDB for use by the bot.  This includes pokémon data (moves, abilities, types, evolutions, etc.), move data (power, type, accuracy, effect, etc.), ability data, and the like.  Scripts for scraping this data should go into the [scripts/ subdirectory](https://github.com/Chronicler0781/turq-bot/tree/master/scripts).  They should modify existing records in the database if possible, and create new records otherwise.

**Comment by nbely** [comment]
All static pokemon data, move data, and ability data was removed from the database and placed into the [data/ subdirectory](https://github.com/nbely/turq-bot/tree/NB/refactoring/data) in order to limit requests to the database for non-state-driven models.
